### ISSUE TITLE
Ruby 2.4.0 FixNum is Deprecated

### ISSUE THREAD

**Issue by jemagee** [thechrisoshow/fractional#8]
I keep getting this error using the gem in my rails 5.0.5 application using Ruby 2.4 (if I knew how to fix it i would)

`/Users/john/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fractional-1.2.0/lib/fractional.rb:16: warning: constant ::Fixnum is deprecated
`

**Comment by thechrisoshow** [comment]
Hi, this should be fixed with the latest version 1.2.1 with this PR https://github.com/thechrisoshow/fractional/pull/9
